/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import React from 'react';

const Disclaimer: React.FC = () => {
    return (
        <div className="bg-white px-6 py-16 lg:px-8">
            <div className="mx-auto max-w-3xl text-base leading-7 text-gray-700">
                <p className="text-base font-semibold leading-7 text-purple-600">Legal</p>
                <h1 className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Disclaimer</h1>
                <p className="mt-6 text-xl leading-8">
                    The virtual try-on service provided by Fit Check is for general informational and entertainment purposes only. The information and generated images are provided in good faith; however, we make no representation or warranty of any kind regarding the accuracy or completeness of the results.
                </p>
                <div className="mt-10 max-w-2xl">
                    <h2 className="mt-16 text-2xl font-bold tracking-tight text-gray-900">AI-Generated Content</h2>
                    <p className="mt-6">
                        The virtual try-on feature is powered by a generative artificial intelligence model. The images produced are simulations. While our goal is to achieve a high degree of realism, the results are an approximation and may not perfectly represent how a garment will look, fit, drape, or feel in real life. Factors such as material, brand-specific sizing, and lighting can affect a garment's real-world appearance.
                    </p>
                    
                    <h2 className="mt-16 text-2xl font-bold tracking-tight text-gray-900">Not a Guarantee of Fit</h2>
                    <p className="mt-6">
                        The Service is a visualization tool, not a fitting guarantee. It is designed to help you explore styles and see a potential look, but it should not be the sole factor in your decision to purchase a garment. We are not responsible for any purchasing decisions made based on the images generated by our Service. Always refer to the manufacturer's or retailer's sizing charts and return policies.
                    </p>

                    <h2 className="mt-16 text-2xl font-bold tracking-tight text-gray-900">No Professional Advice</h2>
                    <p className="mt-6">
                        Fit Check does not provide professional fashion or styling advice. The service is automated and does not substitute for consultation with a professional stylist or tailor.
                    </p>
                    
                    <h2 className="mt-16 text-2xl font-bold tracking-tight text-gray-900">Your Responsibility</h2>
                    <p className="mt-6">
                        Your use of the Service and reliance on any information or generated imagery is solely at your own risk. Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of the Service.
                    </p>
                </div>
            </div>
        </div>
    );
};

export default Disclaimer;